### ISSUE TITLE
admin search should include "to" email address

### ISSUE THREAD

**Issue by steverweber** [pinax/django-mailer#110]
admin message log search should include "to" email address.
if there is good reason not to have it... perhaps have some directions for adding it in the readme.

related
https://github.com/pinax/django-mailer/issues/87

**Comment by spookylukey** [comment]
It's not possible to search that field because the info is not stored in a separate DB column, but inside the pickled message data. We could denormalize and add it as an extra column, but then it becomes difficult to know where to stop. So far we've agreed only on the message ID as a denormalized field, to make it at least possible to locate a specific message - see #57 . The fact that we can also search for it in the admin is a plus - I regard the admin interface as doing the bare minimum for what django-mailer is (i.e. an outgoing email queue).

**Comment by steverweber** [comment]
ah ic and agree to keep it simple.
thanks
