### ISSUE TITLE
Update or add function to create HTML based emails that don't auto-save the message object

### ISSUE THREAD

**Issue by jlward** [pinax/django-mailer#119]
Currently, it looks like there is a method to create message objects without saving them: `make_message`. This tool does not currently allow creation of HTML based messages. At this time, the only way to create HTML based emails is to use `send_html_mail`. Which actually saves the message object. 

In our app, we do not use `send_mail` or `send_html_mail` directly as we want more control over when/how the message object gets saved. To that end, if we wanted to create HTML based emails, we'd have to make a wrapper around `make_message` that replicate some of the code in `send_html_mail`. I have no problem doing this, but I can't be the only person who has run into this.

I propose that either `make_message` is updated to allow for HTML based emails, or `make_html_message` is created to handle the same. Once done, we could update `send_html_mail` to use the new function to reduce code duplication.

Were it me, I would likely lean towards `make_html_message`. That being said, I would be happy to build the solution out and get a PR up. But before I do so, I'd like to make sure I'm not off base here.

**Comment by spookylukey** [comment]
Can you not use Django's [EmailMessage](https://docs.djangoproject.com/en/3.0/topics/email/#the-emailmessage-class) class directly?

**Comment by jlward** [comment]
> Can you not use Django's EmailMessage class directly?

I can, but I was really hoping there would be a tool in this library to help facilitate it. Especially in light of `send_html_mail` doing that. My current plan is to build my own solution in our app until I can use one from here. I'd rather use one from this library than roll my own, but if a PR to do this wouldn't get merged, then I won't have much choice.

**Comment by spookylukey** [comment]
The purpose of django-mailer is to provide a queue for email, and that's it. There were some other functions like `send_html_mail` which exist for historical reasons (from before the time that Django had pluggable email backends, and there wasn't another way to do it).

If something can be implemented in terms of building `EmailMessage` and calling `send` on it, then there isn't a reason for it to be in django-mailer, in fact it would be bad for it to be here, because those utilities could be more widely useful if they weren't tied to django-mailer.

**Comment by jlward** [comment]
> The purpose of django-mailer is to provide a queue for email, and that's it. There were some other functions like send_html_mail which exist for historical reasons (from before the time that Django had pluggable email backends, and there wasn't another way to do it).

I understand that django-mailer is designed to be a queue. And I agree it would be poor form to provide circumventing the queue. I'm not asking that we build something to circumvent the queue. I'm asking that we build a function (that matches `make_message` that builds a `Message` object with an `EmailMultiAlternatives` as `message.email` and attaches the alternative body as `text/html`. With this tool, every project using this library would no longer need to build their own solution for HTML based emails. They could use the implementation in this library. I feel like since the `Email` object is being serialized onto the Message object via a property, making it easy to make HTML based emails would be a big win for this library.

**Comment by spookylukey** [comment]
Sorry, I wasn't talking about circumventing the queue - I was talking about why this functionality would belong in django-mailer, rather than somewhere else?

If I was writing this from scratch, the `send_mail` and `send_html_mail` wrappers wouldn't exist, because Django now has pluggable email backends. I keep them only because of backwards compatibility and the fact that they aren't causing any maintenance problems.

[Very few lines of code are required to build HTML emails](https://docs.djangoproject.com/en/3.0/topics/email/#sending-alternative-content-types) - and doing it in your own utility functions will give you the flexibility you need when you need to extend it for other needs (additional attachments, headers etc.)

**Comment by jlward** [comment]
>  and doing it in your own utility functions will give you the flexibility you need when you need to extend it for other needs (additional attachments, headers etc.)

I respectfully disagree. But it's your library.
