### ISSUE TITLE
Need to find matching MessageLogs by email address

### ISSUE THREAD

**Issue by ebdavison** [pinax/django-mailer#135]
I am trying to match MessageLog entries in the DB with an email address that it was sent to.  In digging into this I can get the to addresses as:

```
In [61]: from mailer.models import MessageLog

In [62]: m = MessageLog.objects.get(pk=1)

In [63]: m.email.to
Out[63]: ['someone@example.com']
```

But, what I need to do is somehow match the email address recipient with an email address for a person in my "person model" so I can display them on a page.  None of the numerous variations have worked and that seems to be because "log.to" is the result of a proplety / "function" and not an actual attribute of the model.

Any tips/pointers/code from anyone who might have already solved this?

**Comment by spookylukey** [comment]
The only way to do it is as follows:

```python
for log in MessageLog.objects.all():
    if "someone@example.com" in log.email.to:
        do_something()
```

This is very bad in terms of performance - you have to load all the `MessageLog` records from the DB to find the one you are interested in. There is no way to do the filtering in the DB, because we don't store that field separately. This is because `MesssageLog` is just not designed for this - it is designed with `django-mailers` needs in mind, not your use case.

The answer is "don't do this". If you need a list of all messages sent to a user, create your own model that has a foreign key to your 'person' model, and use this. At the same time as sending mail (with django-mailer or any other mail backend), you should store a record in this table, storing all the details you need. To populate this table initially you may be able to use the data in the `MessageLog` table. After this initial population, you shouldn't be using `MessageLog` at all.

**Comment by ebdavison** [comment]
Thank you for that code.  I was not able to get that much working before and when/if needed that will definitely come in handy.  As to the separate model, I have started doing this but every once in a while I need to go back to the original message ID and stats returned from the SMTP server so will reserve the above code for an admin details sort of function.  

This is VERY much appreciated.
