### ISSUE TITLE
release new version on PyPI

### ISSUE THREAD

**Issue by bashu** [pinax/django-mailer#17]
Hey,

Can you release new version on PyPI? Latest release 0.1.0 is four years old - https://pypi.python.org/pypi/django-mailer

**Comment by OxanaSachenkova** [comment]
@jtauber do you need any help to get this done?

**Comment by yvess** [comment]
+1
a PyPI release would be really nice

**Comment by paltman** [comment]
@spookylukey it seems that #11 is already fixed by looking at the code, should we just update the issue to reflect status of the code? Also #21 is done.

I am not sure if you are able to push releases or not to PyPI. @jtauber has @spookylukey been added as a maintainer to the PyPI listing?  If not, can you do that so he isn't blocked with pushing a release out?

**Comment by spookylukey** [comment]
I don't seem to have edit privileges for the package on PyPI: https://pypi.python.org/pypi?%3Aaction=pkg_edit&name=django-mailer

If @jtauber can add me, I'll do this.

**Comment by benkonrath** [comment]
Is there any update on this?

**Comment by jtauber** [comment]
@spookylukey what's your PyPI username?

**Comment by spookylukey** [comment]
Yep, "spookylukey", I  have access now, thanks.

**Comment by jtauber** [comment]
Sorry it took so long. And thanks @benkonrath for the final nudge I needed.

**Comment by psi29a** [comment]
+1 :D

**Comment by benkonrath** [comment]
@jtauber Thanks!

**Comment by spookylukey** [comment]
Version 1.0 released now.
